version: '3.8'

services:
  # Frontend (Vue.js)
  frontend:
    image: vvqhuy1999/log-chatbot-frontend:latest
    container_name: log-chatbot-frontend
    ports:
      - "80:80"
    networks:
      - chatlog_chatlog-network
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://backend:8080

networks:
  chatlog_chatlog-network:
    external: true
